### ISSUE TITLE
ar_marker not functioning correctly

### ISSUE THREAD

**Issue by MarcoDotIO** [ROBOTIS-GIT/open_manipulator_perceptions#6]
Hello,

I would like some help diagnosing an issue I'm having with the ar_marker package. I am getting this error whenever opening up ar_pose.launch with the parameter for camera_model set to realsense_d435:

[ERROR] [1571633935.214876304]: Lookup would require extrapolation into the future.  Requested time 3142710556.444393158 but the latest data is at time 1571633935.216517312, when looking up transform from frame [camera_color_optical_frame] to frame [world]

And this error is followed by RViz defaulting to raspicam rather than realsense, in addition to not even turning on the camera when selecting the right one from the camera module. I am currently using the in-package USB-C cable for the realsense, along with using the USB 3.0 port on my laptop. I am on Ubuntu 18.04 (fresh install), and was following the applications section of the open manipulator emanual. Here is a log file filled with some more details of how I have everything set up:
[output.txt](https://github.com/ROBOTIS-GIT/open_manipulator_perceptions/files/3749109/output.txt)

**Comment by yhna** [comment]
Hello, @MaidenOfTheMain 

This error seems to be caused by a difference between the time of the ROS msg published by the camera node and the Rviz time. 
If you're using it on one PC, check to see if other camera-related ros msgs, such as rosbag, are published.
If you are using multiple PCs, follow this [link](http://emanual.robotis.com/docs/en/platform/turtlebot3/faq/#timesync-between-turtlebot3-and-remote-pc)(24.2) to run timesync.
See this [issue](https://answers.ros.org/question/188046/tf-lookup-would-require-extrapolation-into-the-future/) for more details. 

Best Regards

**Comment by MarcoDotIO** [comment]
Alright, I will post the results in the morning. I will try to see if rosbag is being published, since this is only be ran on one PC.

**Comment by MarcoDotIO** [comment]
So here's a list of all the topics, messages, and services being published when running the following command:
`roslaunch open_manipulator_ar_markers ar_pose.launch camera_model:=realsense_d435`

[rosmsg list](https://ghostbin.co/paste/4pr56)
[rostopic list](https://ghostbin.co/paste/ajanb)
[rosservice list](https://ghostbin.co/paste/c7nxm)

No mention of rosbag anywhere within these commands, so I assume that one message isn't being published.

**Comment by MarcoDotIO** [comment]
Hello,

The main issue with ar_pose not reading the trackers wasn't that error, more so using the wrong AR markers (you need to use markers0to8 on the roswiki). I want to ask, keeping this issue open, how would I add additional markers to ar_pose? And as well, does this error have any real impact, because it seems to not have any impact.

**Comment by yhna** [comment]
@MaidenOfTheMain 
Sorry for the late response.

We use the '[ar_track_alvar](http://wiki.ros.org/ar_track_alvar)' ros package to recognize AR markers.
Therefore, please contact 'ar_track_alvar' on how to add markers for recognition.

**Comment by MarcoDotIO** [comment]
Alright then, fair enough. I'll be closing this and if anyone has looked here and still having issues, feel free to either DM me, the robotis team, the team for ar_track_alvar, or reopen this issue.
